library(leaflet)
library(leaflet.extras)
library(ggplot2)
library(dplyr)
library(googleVis)
library(maps)
library(shiny)
library(shinydashboard)
library(lubridate)
library(DT)
library(ggthemes)

NYC_all = read.csv('Manhattan_NYPD_Motor_Vehicle_Collisions_by_Month.csv', stringsAsFactors = F)
miles_added = data.frame("Year" = 2013:2018, "Miles" = c(6.7,5.4,12.4,18.5,20.9,24.9))